### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by webdev-dave** [1moregame/react_appointments#1]
## Feedback:

1. Regarding blocking the user from submitting a contact name duplicate (step 3. in Codecademy project):
___a. the name matching function `isDuplicate` (in ContactsPage.js) is not case-sensitive.
___b. when name is duplicate, the user is left to wonder why the form is not submitting without any error feedback

2. in ContactsPage.js the function you wrote called `isDuplicate `is probably considered a side effect (not sure, correct me if I'm wrong) and should therefore be placed inside a `useEffect()` hook

3. Also in ContactsPage.js in the return function while passing the state settter functions to ContactForm you pass them like this:
`setX={(value) => setX(value)}`
This can be done in a shorter format like so:
`setX={setX} `

4. In the appointment form, at ContactPicker.js the `<select />` element has no measure to prevent the user from submitting the default option (select contact)  

## I Really liked:
1. How you pre-loaded a default sample for contacts and appointments.
2. The delete button on the saved contacts and appointments is a brilliant addition!! 
3. pre-loading the current time and date in the appointment form is another brilliant feature
4. placing time and date side by side in appointment form is a great and practical design  

## Solution for clearing previous contact from appointment form

I managed to come up with an alternative workaround approach for clearing the previously selected contact. The solution involved creating a new state setter with a state value called `clearOnSubmit` (set to false). Then, in AppointmentPage.js I wrote a new useEffect hook with a timer in it.  I also passed `clearOnSubmit` as a prop to ContactPicker.js

Then, in ContactPicker.js I set the mapping of the options array (array of contacts) on the condition that `clearOnSubmit` is false. When `clearOnSubmit` is true (during a submit) the form ends up resetting to the initial default `<option>Select Contact <opton/>` because it is the only option that exists for that moment. Shortly thereafter, the timed `useEffect()` quickly resets (after a half-second) `clearOnSubmit` to false which then allows the list of contacts to re-render for selection only this time around, the select element no longer loads the previously selected element.

I tried my best but It's a bit hard to explain my workaround solution without viewing the actual code. If you'd like, my solution should be viewable once I push my most recent edits to GitHub. (to avoid confusion, I am waiting for you to code review my initial version of the code. Once I receive your feedback, I will make finish formatting all my updates and push it all to GitHub)  

### P.s.
I really enjoyed reviewing your code and learned a lot from it. Looking forward to hearing back from you and I hope we get to collaborate some more in the future. 

Cheers and all the best, 
David

**Comment by 1moregame** [comment]
This was a great experience!  I likewise learned a lot from your code.  I didn't realize/remember that you can default the key to an object to the variable name used to set it.  What a great shortcut!  

Interestingly enough, I looked at the Codeacademy Solution today and their solution fails to reset the dropdown as well!  That was disappointing.  I think your solution makes sense, I would like to see it in action.  Thanks for the patience in pushing the code and apologies for the delay.  I was traveling all weekend and work has been a nightmare.

Jacob

**Comment by 1moregame** [comment]
Early start today...I wanted to follow up on a couple of items too.  

I have moved forward to fix items 1-3 in your list.  Item 4 however was intentional.  I decided that there is a chance you may want an appointment that doesn't include a contact.  Perhaps it is a personal appointment or a form of reminder.  The only requirements.  I intentionally did the same when creating a contact.  A name is required, but email and phone are not.  You may not have 1 or both pieces of information.  A future extension of this would allow for changes to existing contacts/appointments. 

Thanks again, this exercise was really valuable and I would be interested in pairing up for a code review again.  Perhaps a pair programming exercise sometime as well if you are interested.

Jacob

**Comment by webdev-dave** [comment]
Hi, Jacob just thanks for following up.  Regarding step 4, you make a valid point about the case of a user wanting to save a contact name without having both the email and phone number. 

I too have thoroughly enjoyed the reviewing process. I would definitely be interested in connecting some more in the future. Let's be in touch via email so we can learn a bit more about each other. Feel free to reach out, my email address is: elidovrichcoding@gmail.com
